project:
  type: website
  output-dir: docs

website:
  title: "Introduction to HPC"
  navbar:
    background: primary
    left:
      - href: setup.qmd
        text: "Setup"
      - text: Concepts
        menu:
          - text: "General HPC"
            href: notebooks/02_connect.qmd
          - text: "Artemis Specific"
            href: notebooks/01_context.qmd
      - text: Running Code on Artemis
        menu:
          - text: "Hello World on HPC"
            href: notebooks/03_step1.qmd
          - text: "Running Common Software on HPC"
            href: notebooks/03_step2.qmd
      - text: Research Data Storage
        menu:
          - text: "Research Data Store"
            href: notebooks/03_step3.qmd
      - text: More resources
        menu:
          - text: "More resources"
            href: notebooks/03_step4.qmd



  cookie-consent:
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   css: [styles.scss]
   quarto-margin-sidebar:
     max-width: 1000px
   theme: simplex
      # light: flatly
      # dark: darkly

   code-link: true
   code-fold: false
