project:
  type: website
  output-dir: docs

website:
  title: "Introduction to High Performance Computing"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: Concepts
        menu:
          - text: "General HPC"
            href: 02_connect.html
          - text: "Artemis Specific"
            href: 01_context.html
      - text: Running Code on Artemis
        menu:
          - text: "Hello World on HPC"
            href: 03_step1.html
          - text: "Running Common Software on HPC"
            href: 403_step2.html
      - text: Research Data Storage
        menu:
          - text: "Research Data Store"
            href: 03_step3.html
      - text: More resources
        menu:
          - text: "More resources"
            href: 03_step4.html



  cookie-consent:
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  page-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   css: [styles.scss]
   quarto-margin-sidebar:
     max-width: 1000px
   theme:
      light: flatly
      dark: darkly

   code-link: true
   code-fold: false
