---
title: "Introduction to High Performance Computing"
output:
  html_document:
    toc: false
    toc_float: false
---


Introduces Sydney’s High Performance Computer (HPC), ‘Artemis’. We cover connecting and navigating Artemis, available software, and how to submit and monitor jobs using the PBS Pro scheduler. Students and staff who would like to learn how to run compute jobs on Artemis HPC. 

All data used in the course can be found [here](https://github.com/kmarsyd/IntroHPCData/tree/main). "Download ZIP" under the green code button can be used to download it if you are unfamiliar with git. 

## Watch the Recording

This was delivered as an interactive workshop at Sydney. If you find yourself here in the future feel free to watch the recording:

Coming Soon!

## Contributors

* [Kris](https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/our-staff.html) SIH



## Course pre-requisites and setup requirements

No previous programming experience is required, this training course will introduce you to fundamentals of the various tools (unix/linux, HPC) as required. Training will be delivered online, so you will need access to a modern computer with a stable internet connection. Participants must have a valid Sydney University Unikey and will require the Sydney VPN and a terminal client (as per the [Setup Instructions](./setup.html) provided).

## The Sydney Informatics hub

This course is brought to you by [Sydney Informatics Hub (SIH)](https://informatics.sydney.edu.au) is a Core Research Facility of the University of Sydney. Core Research Facilities centralise essential research equipment and services that would otherwise be too expensive or impractical for individual Faculties to purchase and maintain

## Venue

Online via Zoom, a link will be shared with registered participants.

#### Zoom etiquette and how we interact

Sessions will be recorded and added to this page. Please interrupt whenever you want! Ideally, have your camera on and interact as much as possible. There will be someone monitoring the chat-window for any questions you would like to post there.  Extending for a three-hour duration, our Zoom session incorporates regular breaks and a blend of demonstrative and hands-on material.


## Code of Conduct

As a University of Sydney course, we also want to make sure peopele are aware of our code of conduct.
Feel free to move this to an about page as needed.

Example standard Code of Conduct statement:

We expect all attendees of our training to follow our code of conduct, including bullying, harassment and discrimination prevention policies.

In order to foster a positive and professional learning environment we encourage the following kinds of behaviours at all our events and on our platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

Our full CoC, with incident reporting guidelines, is available [Here](https://sydney-informatics-hub.github.io/codeofconduct/).



## Schedule

|  |  |
| --- | :--- |
| **In-depth** |
|   | [Artemis HPC](notebooks/01_context.qmd) |


## Acknowledgements

If you do use Artemis for your research, please acknowledge us! This ensures that we continue to get the funding we need to provide you with what is really a first-grade computing resource. And don’t forget to apply to the Publication Incentive! A suggested acknowledgment might say:

`The authors acknowledge the Sydney Informatics Hub and the University of Sydney’s high performance computing cluster, Artemis, for providing the computing resources that have contributed to the results reported herein`


## Before Training (10 mins)

To hit the ground running during the training please:

* 1. Read and install the neccessary apps in the [Setup Instructions](./setup.html).

* 2. Read the general HPC content under [Concepts](./notebooks/01_context.qmd).


